<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>confluence</string>
      <string>markup</string>
      <string>wiki</string>
    </array>
    <key>firstLineMatch</key>
    <string>confluence</string>
    <key>keyEquivalent</key>
    <string>^~C</string>
    <key>name</key>
    <string>Confluence markup</string>
    <key>scopeName</key>
    <string>text.html.confluence</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#paragraph</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>paragraph</key>
      <dict>
        <key>name</key>
        <string>meta.paragraph.confluence</string>
        <key>begin</key>
        <string>^</string>
        <key>end</key>
        <string>^$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#hr</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#heading</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#inline</string>
          </dict>
        </array>
      </dict>
      <key>heading</key>
      <dict>
        <key>name</key>
        <string>markup.heading.confluence</string>
        <key>match</key>
        <string>(?:^|\G)((h[1-6])\.\s+(.*?)(\s+)?\s*)$</string>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>meta.tag.$2.confluence</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>text.html.heading.confluence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#inline</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#inline</string>
          </dict>
        </array>
      </dict>
      <key>hr</key>
      <dict>
        <key>name</key>
        <string>markup.hr.confluence</string>
        <key>match</key>
        <string>(-{4,})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.tag.hr.confluence</string>
          </dict>
        </dict>
      </dict>
      <key>inline</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#bold</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#italic</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#emoticon</string>
          </dict>
        </array>
      </dict>
      <key>emoticon</key>
      <dict>
        <key>name</key>
        <string>markup.emoticon.confluence</string>
        <key>match</key>
        <string>(\B)(:P|:D|:\)|:\(|;\)|\(y\)|\(n\)|\(i\)|\(\/\)|\(x\)|\(!\))\1</string>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>text.html.image.emoticon.confluence</string>
          </dict>
        </dict>
      </dict>
      <key>bold</key>
      <dict>
        <key>name</key>
        <string>markup.bold.confluence</string>
        <key>match</key>
        <string>(\*)([^\*]*)(\1)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.tag.b.begin.confluence</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>text.html.bold.element.confluence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#inline</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>meta.tag.b.end.confluence</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#inline</string>
          </dict>
        </array>
      </dict>
      <key>italic</key>
      <dict>
        <key>name</key>
        <string>markup.italic.confluence</string>
        <key>match</key>
        <string>(\_)([^\_]*)(\1)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.tag.i.begin.confluence</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>text.html.italic.element.confluence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#inline</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>meta.tag.i.end.confluence</string>
          </dict>
        </dict>
      </dict>
    </dict>
    <key>uuid</key>
    <string>2D045A75-E4D7-4904-8766-D6234F10FCA1</string>
  </dict>
</plist>
