<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>confluence</string>
      <string>markup</string>
      <string>wiki</string>
    </array>
    <key>firstLineMatch</key>
    <string>confluence</string>
    <key>keyEquivalent</key>
    <string>^~C</string>
    <key>name</key>
    <string>Confluence markup</string>
    <key>scopeName</key>
    <string>text.html.confluence</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#paragraph</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>paragraph</key>
      <dict>
        <key>name</key>
        <string>text.html.paragraph.confluence</string>
        <key>begin</key>
        <string>^</string>
        <key>end</key>
        <string>^$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#escape-char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#hr</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#heading</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#table</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#inline</string>
          </dict>
        </array>
      </dict>
      <key>escape-char</key>
      <dict>
        <key>name</key>
        <string>markup.constant.escape.confluence</string>
        <key>match</key>
        <string>(\\)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.ignore.escape.confluence</string>
          </dict>
        </dict>
      </dict>
      <key>hr</key>
      <dict>
        <key>name</key>
        <string>markup.hr.confluence</string>
        <key>match</key>
        <string>(-{4,})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.tag.hr.confluence</string>
          </dict>
        </dict>
      </dict>
      <key>heading</key>
      <dict>
        <key>name</key>
        <string>markup.heading.confluence</string>
        <key>match</key>
        <string>(?:^|\G)((h[1-6])(\.\s+)(.*?)(\s+)?\s*)$</string>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>meta.tag.$2.confluence</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>meta.ignore.$2.confluence</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>text.html.heading.confluence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#inline</string>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      <key>table</key>
      <dict>
        <key>name</key>
        <string>markup.other.table.confluence</string>
        <key>begin</key>
        <string>^\s*(?=\|)</string>
        <key>end</key>
        <string>^(?!\s*\|)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>markup.other.table.header.confluence</string>
            <key>begin</key>
            <string>\|\|</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.table.header.confluence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\|\|?|\n)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#inline</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>markup.other.table.cell.confluence</string>
            <key>begin</key>
            <string>\|(?!\|)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.table.cell.confluence</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\||\n)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#inline</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>inline</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#link</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#line-break</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#mdash</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#ndash</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#emoticon</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#bold</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#italic</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#citation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#inserted</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#superscript</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#subscript</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#deleted</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#monospaced</string>
          </dict>
        </array>
      </dict>
      <key>link</key>
      <dict>
        <key>name</key>
        <string>markup.link.confluence</string>
        <key>match</key>
        <string>(\[)(?:([^|]*?)(\|))?([^\[]*?[^\\|\s])(\])</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.tag.a.confluence</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>text.html.link.element.confluence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#inline</string>
              </dict>
            </array>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>meta.attribute.href.confluence</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>meta.close.a.confluence</string>
          </dict>
        </dict>
      </dict>
      <key>line-break</key>
      <dict>
        <key>name</key>
        <string>markup.line-break.confluence</string>
        <key>match</key>
        <string>(\\\\)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.tag.br.confluence</string>
          </dict>
        </dict>
      </dict>
      <key>mdash</key>
      <dict>
        <key>name</key>
        <string>markup.mdash.confluence</string>
        <key>match</key>
        <string>\B(-{3})\B</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>text.html.mdash.element.confluence</string>
          </dict>
        </dict>
      </dict>
      <key>ndash</key>
      <dict>
        <key>name</key>
        <string>markup.ndash.confluence</string>
        <key>match</key>
        <string>\B(-{2})\B</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>text.html.ndash.element.confluence</string>
          </dict>
        </dict>
      </dict>
      <key>emoticon</key>
      <dict>
        <key>name</key>
        <string>markup.emoticon.confluence</string>
        <key>match</key>
        <string>(\B)(:P|:D|:\)|:\(|;\)|\(y\)|\(n\)|\(i\)|\(\/\)|\(x\)|\(!\))\1</string>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>text.html.image.emoticon.confluence</string>
          </dict>
        </dict>
      </dict>
      <key>bold</key>
      <dict>
        <key>name</key>
        <string>markup.bold.confluence</string>
        <key>match</key>
        <string>(\*)([^\*]*)(\1)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.tag.strong.confluence</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>text.html.bold.element.confluence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#inline</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>meta.close.strong.confluence</string>
          </dict>
        </dict>
      </dict>
      <key>italic</key>
      <dict>
        <key>name</key>
        <string>markup.italic.confluence</string>
        <key>match</key>
        <string>(\b_|\{_\})([^_]*)(_)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.tag.i.confluence</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>text.html.italic.element.confluence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#inline</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>meta.close.i.confluence</string>
          </dict>
        </dict>
      </dict>
      <key>citation</key>
      <dict>
        <key>name</key>
        <string>markup.citation.confluence</string>
        <key>match</key>
        <string>(\?{2})(.*)(\1)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.tag.cite.confluence</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>text.html.citation.element.confluence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#inline</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>meta.tag.cite.close.confluence</string>
          </dict>
        </dict>
      </dict>
      <key>inserted</key>
      <dict>
        <key>name</key>
        <string>markup.inserted.confluence</string>
        <key>match</key>
        <string>(\+)(.*)(\1)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.tag.ins.confluence</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>text.html.inserted.element.confluence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#inline</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>meta.close.ins.confluence</string>
          </dict>
        </dict>
      </dict>
      <key>superscript</key>
      <dict>
        <key>name</key>
        <string>markup.superscript.confluence</string>
        <key>match</key>
        <string>(\^)([^\^]*)(\1)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.tag.sup.confluence</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>text.html.superscript.element.confluence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#inline</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>meta.tag.sup.close.confluence</string>
          </dict>
        </dict>
      </dict>
      <key>subscript</key>
      <dict>
        <key>name</key>
        <string>markup.subscript.confluence</string>
        <key>match</key>
        <string>(~)([^~]*)(\1)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.tag.sub.confluence</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>text.html.subscript.element.confluence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#inline</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>meta.close.sub.confluence</string>
          </dict>
        </dict>
      </dict>
      <key>deleted</key>
      <dict>
        <key>name</key>
        <string>markup.deleted.confluence</string>
        <key>match</key>
        <string>\B(-)(.*)(\1)\B</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.tag.del.confluence</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>text.html.deleted.element.confluence</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#inline</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>meta.close.del.confluence</string>
          </dict>
        </dict>
      </dict>
      <key>monospaced</key>
      <dict>
        <key>name</key>
        <string>markup.raw.confluence</string>
        <key>match</key>
        <string>(\{{2})(.*?)(\}{2})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.tag.code.confluence</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>text.html.raw.element.confluence</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>meta.close.code.confluence</string>
          </dict>
        </dict>
      </dict>
    </dict>
    <key>uuid</key>
    <string>2D045A75-E4D7-4904-8766-D6234F10FCA1</string>
  </dict>
</plist>
