name: vscode confluence markup extension

on:
  push:
    branches:
      - feature/*
      - main
  pull_request:
    branches:
      - main
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 14.x
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm test
