name: vscode confluence markup extension

on:
  push:
    branches:
      - feature/*
      - main
  pull_request:
    branches:
      - main
jobs:
  "Test Markup Parser":
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: sudo apt-get install -y xvfb
    - run: xvfb-run --auto-servernum npm test
