name: Matrix extension tests

on:
  push:
    branches:
      - feature/*
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: install dependencies
      uses: npm install
    - name: test markup parsing
      uses: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - name: test markup parsing
      uses: npm test
      if: runner.os != 'Linux'
